version: '3.4'

services:
    webapp : 
        environment: 
            ConnectionStrings__DefaultConnection: Server=db,1433;Database=undersea;User=SA;Password=P.ssw0rd;
            ConnectionStrings__HangfireConnection : Server=db,1433;Database=undersea;User=SA;Password=P.ssw0rd;
        ports: 
            - "8088:80"
    nodeapp:
        ports: 
            - "8080:80"
    db : 
        ports:
            - "1433:1433"
        volumes:
            - ./my-vol:/var/opt/mssql:rw
        environment:
            SA_PASSWORD: "P.ssw0rd"
            ACCEPT_EULA: "Y"

volumes : 
    my-vol :
        name : my-volume-001